package com.model;

import java.util.List;

/**
 * TCatelog generated by MyEclipse Persistence Tools
 */
public class TCatelog implements java.io.Serializable
{
	// Fields
	private Integer catelogId;

	private String catelogName;

	private String catelogMiaoshu;
	
	private String catelogDel;
	
	private List newsList;
	private List childList;
	private int pid;

	// Constructors

	/** default constructor */
	public TCatelog()
	{
	}

	/** full constructor */
	public TCatelog(String catelogName, String catelogMiaoshu)
	{
		this.catelogName = catelogName;
		this.catelogMiaoshu = catelogMiaoshu;
	}

	public List getChildList() {
		return childList;
	}

	public void setChildList(List childList) {
		this.childList = childList;
	}

	public int getPid() {
		return pid;
	}

	public void setPid(int pid) {
		this.pid = pid;
	}

	public Integer getCatelogId()
	{
		return this.catelogId;
	}

	public String getCatelogDel()
	{
		return catelogDel;
	}

	public List getNewsList()
	{
		return newsList;
	}

	public void setNewsList(List newsList)
	{
		this.newsList = newsList;
	}

	public void setCatelogDel(String catelogDel)
	{
		this.catelogDel = catelogDel;
	}

	public void setCatelogId(Integer catelogId)
	{
		this.catelogId = catelogId;
	}

	public String getCatelogName()
	{
		return this.catelogName;
	}

	public void setCatelogName(String catelogName)
	{
		this.catelogName = catelogName;
	}

	public String getCatelogMiaoshu()
	{
		return this.catelogMiaoshu;
	}

	public void setCatelogMiaoshu(String catelogMiaoshu)
	{
		this.catelogMiaoshu = catelogMiaoshu;
	}
}