package com.model;

import java.util.Date;

/**
 * TNews generated by MyEclipse Persistence Tools
 */
public class TNews implements java.io.Serializable
{

	// Fields
	private Integer newsId;

	private String newsTitle;

	private String newsContent;

	private String newsDate;

	private int catelogId;
	
	private String catelogName;
	private String fujian;

	// Constructors
	public String getFujian() {
		return fujian;
	}

	public void setFujian(String fujian) {
		this.fujian = fujian;
	}

	/** default constructor */
	public TNews()
	{
	}

	public Integer getNewsId()
	{
		return this.newsId;
	}

	public void setNewsId(Integer newsId)
	{
		this.newsId = newsId;
	}

	public String getCatelogName()
	{
		return catelogName;
	}

	public void setCatelogName(String catelogName)
	{
		this.catelogName = catelogName;
	}

	public String getNewsTitle()
	{
		return this.newsTitle;
	}

	public void setNewsTitle(String newsTitle)
	{
		this.newsTitle = newsTitle;
	}

	public String getNewsContent()
	{
		return this.newsContent;
	}

	public void setNewsContent(String newsContent)
	{
		this.newsContent = newsContent;
	}

	public String getNewsDate()
	{
		return this.newsDate;
	}

	public void setNewsDate(String newsDate)
	{
		this.newsDate = newsDate;
	}

	public int getCatelogId()
	{
		return catelogId;
	}

	public void setCatelogId(int catelogId)
	{
		this.catelogId = catelogId;
	}

}