package com.model;

import java.util.Date;

/**
 * TUser generated by MyEclipse Persistence Tools
 */

public class TUser implements java.io.Serializable
{
	// Fields
	private Integer userId;

	private String userName;

	private String userPw;

	private int userType;

	private String userRealname;

	private String userAddress;

	private String userSex;

	private String userTel;

	private String userEmail;

	private String userQq;

	private String userMan;

	private String userAge;

	private String userBirthday;

	private String userXueli;
	
	private String userDel;
	
	private String zt;

	// Constructors

	/** default constructor */
	public TUser()
	{
	}
	// Property accessors

	public Integer getUserId()
	{
		return this.userId;
	}

	public String getUserDel()
	{
		return userDel;
	}

	public void setUserDel(String userDel)
	{
		this.userDel = userDel;
	}

	public void setUserId(Integer userId)
	{
		this.userId = userId;
	}

	public int getUserType()
	{
		return userType;
	}

	public void setUserType(int userType)
	{
		this.userType = userType;
	}

	public String getUserName()
	{
		return this.userName;
	}

	public void setUserName(String userName)
	{
		this.userName = userName;
	}

	public String getUserPw()
	{
		return this.userPw;
	}

	public void setUserPw(String userPw)
	{
		this.userPw = userPw;
	}

	public String getUserRealname()
	{
		return this.userRealname;
	}

	public void setUserRealname(String userRealname)
	{
		this.userRealname = userRealname;
	}

	public String getUserAddress()
	{
		return this.userAddress;
	}

	public void setUserAddress(String userAddress)
	{
		this.userAddress = userAddress;
	}

	public String getUserSex()
	{
		return this.userSex;
	}

	public void setUserSex(String userSex)
	{
		this.userSex = userSex;
	}

	public String getUserTel()
	{
		return this.userTel;
	}

	public void setUserTel(String userTel)
	{
		this.userTel = userTel;
	}

	public String getUserEmail()
	{
		return this.userEmail;
	}

	public void setUserEmail(String userEmail)
	{
		this.userEmail = userEmail;
	}

	public String getUserQq()
	{
		return this.userQq;
	}

	public void setUserQq(String userQq)
	{
		this.userQq = userQq;
	}

	public String getUserMan()
	{
		return this.userMan;
	}

	public void setUserMan(String userMan)
	{
		this.userMan = userMan;
	}

	public String getUserAge()
	{
		return this.userAge;
	}

	public void setUserAge(String userAge)
	{
		this.userAge = userAge;
	}

	public String getUserBirthday()
	{
		return this.userBirthday;
	}

	public void setUserBirthday(String userBirthday)
	{
		this.userBirthday = userBirthday;
	}

	public String getUserXueli()
	{
		return this.userXueli;
	}

	public void setUserXueli(String userXueli)
	{
		this.userXueli = userXueli;
	}

	public String getZt() {
		return zt;
	}

	public void setZt(String zt) {
		this.zt = zt;
	}
}